-i-m-p-o-r-t- -'-p-a-c-k-a-g-e-:-f-l-u-t-t-e-r-/-m-a-t-e-r-i-a-l-.-d-a-r-t-'-;--
-i-m-p-o-r-t- -'-f-i-r-e-b-a-s-e-_-o-p-t-i-o-n-s-.-d-a-r-t-'-;--
-i-m-p-o-r-t- -'-p-a-c-k-a-g-e-:-f-i-r-e-b-a-s-e-_-c-o-r-e-/-f-i-r-e-b-a-s-e-_-c-o-r-e-.-d-a-r-t-'-;--
-i-m-p-o-r-t- -'-f-i-r-e-b-a-s-e-_-o-p-t-i-o-n-s-.-d-a-r-t-'-;--
-i-m-p-o-r-t- -'-p-a-c-k-a-g-e-:-h-i-v-e-_-f-l-u-t-t-e-r-/-h-i-v-e-_-f-l-u-t-t-e-r-.-d-a-r-t-'-;--
--
-i-m-p-o-r-t- -'-f-i-r-e-b-a-s-e-_-o-p-t-i-o-n-s-.-d-a-r-t-'-;--
-i-m-p-o-r-t- -'-a-p-p-/-s-t-a-t-e-/-m-o-d-e-l-s-.-d-a-r-t-'-;--
-i-m-p-o-r-t- -'-f-i-r-e-b-a-s-e-_-o-p-t-i-o-n-s-.-d-a-r-t-'-;--
-i-m-p-o-r-t- -'-a-p-p-/-s-c-r-e-e-n-s-/-i-n-v-e-n-t-o-r-y-_-s-c-r-e-e-n-.-d-a-r-t-'-;--
-i-m-p-o-r-t- -'-f-i-r-e-b-a-s-e-_-o-p-t-i-o-n-s-.-d-a-r-t-'-;--
-i-m-p-o-r-t- -'-a-p-p-/-s-c-r-e-e-n-s-/-s-e-t-t-i-n-g-s-_-s-c-r-e-e-n-.-d-a-r-t-'-;--
-i-m-p-o-r-t- -'-f-i-r-e-b-a-s-e-_-o-p-t-i-o-n-s-.-d-a-r-t-'-;--
-i-m-p-o-r-t- -'-a-p-p-/-s-c-r-e-e-n-s-/-s-a-l-e-s-_-s-c-r-e-e-n-.-d-a-r-t-'-;--
-i-m-p-o-r-t- -'-f-i-r-e-b-a-s-e-_-o-p-t-i-o-n-s-.-d-a-r-t-'-;--
-i-m-p-o-r-t- -'-a-p-p-/-t-h-e-m-e-/-r-a-u-l-i-_-t-h-e-m-e-.-d-a-r-t-'-;--
--
-i-m-p-o-r-t- -'-f-i-r-e-b-a-s-e-_-o-p-t-i-o-n-s-.-d-a-r-t-'-;--
-F-u-t-u-r-e-<-v-o-i-d->- -m-a-i-n-(-)- -a-s-y-n-c- -{--
- - -W-i-d-g-e-t-s-F-l-u-t-t-e-r-B-i-n-d-i-n-g-.-e-n-s-u-r-e-I-n-i-t-i-a-l-i-z-e-d-(-)-;--
--
- - -a-w-a-i-t- -F-i-r-e-b-a-s-e-.-i-n-i-t-i-a-l-i-z-e-A-p-p-(-o-p-t-i-o-n-s-:- -D-e-f-a-u-l-t-F-i-r-e-b-a-s-e-O-p-t-i-o-n-s-.-c-u-r-r-e-n-t-P-l-a-t-f-o-r-m-)-;--
- - -a-w-a-i-t- -H-i-v-e-.-i-n-i-t-F-l-u-t-t-e-r-(-)-;--
- - -f-i-n-a-l- -b-o-x- -=- -a-w-a-i-t- -H-i-v-e-.-o-p-e-n-B-o-x-(-'-r-a-u-l-i-_-b-o-x-'-)-;--
--
- - -r-u-n-A-p-p-(-A-p-p-S-t-a-t-e-S-c-o-p-e-(--
- - - - -n-o-t-i-f-i-e-r-:- -A-p-p-S-t-a-t-e-(-b-o-x-)-,--
- - - - -c-h-i-l-d-:- -c-o-n-s-t- -R-a-u-l-i-A-p-p-(-)-,--
- - -)-)-;--
-}--
--
-c-l-a-s-s- -A-p-p-S-t-a-t-e- -e-x-t-e-n-d-s- -C-h-a-n-g-e-N-o-t-i-f-i-e-r- -{--
- - -f-i-n-a-l- -B-o-x- -b-o-x-;--
- - -A-p-p-S-t-a-t-e-(-t-h-i-s-.-b-o-x-)- -{--
- - - - -_-l-o-a-d-A-l-l-(-)-;--
- - -}--
--
- - -/-/- -=-=-=-=-=- -C-o-n-f-i-g- -g-l-o-b-a-l--
- - -S-t-r-i-n-g- -t-e-n-a-n-t-N-a-m-e- -=- -"-S-u-c-u-r-s-a-l- -P-r-i-n-c-i-p-a-l-"-;--
- - -S-t-r-i-n-g- -b-r-a-n-c-h-N-a-m-e- -=- -"-S-u-c-u-r-s-a-l- -P-r-i-n-c-i-p-a-l-"-;--
- - -S-t-r-i-n-g- -l-o-c-a-l-e- -=- -"-e-s-_-U-S-"-;--
- - -S-t-r-i-n-g- -c-u-r-r-e-n-c-y-C-o-d-e- -=- -"-U-S-D-"-;--
- - -S-t-r-i-n-g- -d-e-c-i-m-a-l-S-e-p- -=- -"-.-"-;--
- - -S-t-r-i-n-g- -t-h-o-u-s-a-n-d-S-e-p- -=- -"-,-"-;--
- - -b-o-o-l- -t-a-x-E-n-a-b-l-e-d- -=- -f-a-l-s-e-;--
- - -d-o-u-b-l-e- -t-a-x-R-a-t-e- -=- -0-.-0-;--
- - -S-t-r-i-n-g- -t-a-x-M-o-d-e- -=- -"-i-n-c-l-u-s-i-v-e-"-;--
--
- - -/-/- -=-=-=-=-=- -T-e-m-a--
- - -T-h-e-m-e-S-c-h-e-m-e- -t-h-e-m-e-S-c-h-e-m-e- -=- -T-h-e-m-e-S-c-h-e-m-e-.-r-a-u-l-i-B-l-u-e-G-o-l-d-;--
--
- - -/-/- -=-=-=-=-=- -V-e-n-t-a-s--
- - -f-i-n-a-l- -L-i-s-t-<-M-a-p-<-S-t-r-i-n-g-,- -d-y-n-a-m-i-c->->- -s-a-l-e-s- -=- -[-]-;--
--
- - -/-/- -=-=-=-=-=- -I-n-v-e-n-t-a-r-i-o--
- - -f-i-n-a-l- -L-i-s-t-<-I-n-v-e-n-t-o-r-y-I-t-e-m->- -i-n-v-e-n-t-o-r-y-I-t-e-m-s- -=- -[-]-;--
- - -f-i-n-a-l- -L-i-s-t-<-S-t-o-c-k-M-o-v-e->- -s-t-o-c-k-M-o-v-e-s- -=- -[-]-;--
--
- - -v-o-i-d- -_-l-o-a-d-A-l-l-(-)- -{--
- - - - -t-e-n-a-n-t-N-a-m-e- -=- -(-b-o-x-.-g-e-t-(-"-t-e-n-a-n-t-N-a-m-e-"-)- -?-?- -t-e-n-a-n-t-N-a-m-e-)-.-t-o-S-t-r-i-n-g-(-)-;--
- - - - -b-r-a-n-c-h-N-a-m-e- -=- -(-b-o-x-.-g-e-t-(-"-b-r-a-n-c-h-N-a-m-e-"-)- -?-?- -b-r-a-n-c-h-N-a-m-e-)-.-t-o-S-t-r-i-n-g-(-)-;--
- - - - -l-o-c-a-l-e- -=- -(-b-o-x-.-g-e-t-(-"-l-o-c-a-l-e-"-)- -?-?- -l-o-c-a-l-e-)-.-t-o-S-t-r-i-n-g-(-)-;--
- - - - -c-u-r-r-e-n-c-y-C-o-d-e- -=- -(-b-o-x-.-g-e-t-(-"-c-u-r-r-e-n-c-y-C-o-d-e-"-)- -?-?- -c-u-r-r-e-n-c-y-C-o-d-e-)-.-t-o-S-t-r-i-n-g-(-)-;--
- - - - -d-e-c-i-m-a-l-S-e-p- -=- -(-b-o-x-.-g-e-t-(-"-d-e-c-i-m-a-l-S-e-p-"-)- -?-?- -d-e-c-i-m-a-l-S-e-p-)-.-t-o-S-t-r-i-n-g-(-)-;--
- - - - -t-h-o-u-s-a-n-d-S-e-p- -=- -(-b-o-x-.-g-e-t-(-"-t-h-o-u-s-a-n-d-S-e-p-"-)- -?-?- -t-h-o-u-s-a-n-d-S-e-p-)-.-t-o-S-t-r-i-n-g-(-)-;--
- - - - -t-a-x-E-n-a-b-l-e-d- -=- -(-b-o-x-.-g-e-t-(-"-t-a-x-E-n-a-b-l-e-d-"-)- -?-?- -t-a-x-E-n-a-b-l-e-d-)- -=-=- -t-r-u-e-;--
- - - - -t-a-x-R-a-t-e- -=- -(-(-b-o-x-.-g-e-t-(-"-t-a-x-R-a-t-e-"-)- -?-?- -t-a-x-R-a-t-e-)- -a-s- -n-u-m-)-.-t-o-D-o-u-b-l-e-(-)-;--
- - - - -t-a-x-M-o-d-e- -=- -(-b-o-x-.-g-e-t-(-"-t-a-x-M-o-d-e-"-)- -?-?- -t-a-x-M-o-d-e-)-.-t-o-S-t-r-i-n-g-(-)-;--
--
- - - - -f-i-n-a-l- -t-h-e-m-e-R-a-w- -=- -(-b-o-x-.-g-e-t-(-"-t-h-e-m-e-S-c-h-e-m-e-"-)- -?-?- -T-h-e-m-e-S-c-h-e-m-e-.-r-a-u-l-i-B-l-u-e-G-o-l-d-.-n-a-m-e-)-.-t-o-S-t-r-i-n-g-(-)-;--
- - - - -t-h-e-m-e-S-c-h-e-m-e- -=- -T-h-e-m-e-S-c-h-e-m-e-.-v-a-l-u-e-s-.-f-i-r-s-t-W-h-e-r-e-(--
- - - - - - -(-e-)- -=->- -e-.-n-a-m-e- -=-=- -t-h-e-m-e-R-a-w-,--
- - - - - - -o-r-E-l-s-e-:- -(-)- -=->- -T-h-e-m-e-S-c-h-e-m-e-.-r-a-u-l-i-B-l-u-e-G-o-l-d-,--
- - - - -)-;--
--
- - - - -f-i-n-a-l- -r-a-w-S-a-l-e-s- -=- -b-o-x-.-g-e-t-(-"-s-a-l-e-s-"-)-;--
- - - - -f-i-n-a-l- -l-s- -=- -(-r-a-w-S-a-l-e-s- -i-s- -L-i-s-t-)- -?- -r-a-w-S-a-l-e-s-.-c-a-s-t-<-d-y-n-a-m-i-c->-(-)- -:- -<-d-y-n-a-m-i-c->-[-]-;--
- - - - -s-a-l-e-s--
- - - - - - -.-.-c-l-e-a-r-(-)--
- - - - - - -.-.-a-d-d-A-l-l-(-l-s-.-w-h-e-r-e-T-y-p-e-<-M-a-p->-(-)-.-m-a-p-(-(-m-)- -=->- -M-a-p-<-S-t-r-i-n-g-,- -d-y-n-a-m-i-c->-.-f-r-o-m-(-m-)-)-)-;--
--
- - - - -f-i-n-a-l- -r-a-w-I-t-e-m-s- -=- -b-o-x-.-g-e-t-(-"-i-n-v-e-n-t-o-r-y-_-i-t-e-m-s-"-)-;--
- - - - -f-i-n-a-l- -r-a-w-M-o-v-e-s- -=- -b-o-x-.-g-e-t-(-"-s-t-o-c-k-_-m-o-v-e-s-"-)-;--
- - - - -f-i-n-a-l- -l-i- -=- -(-r-a-w-I-t-e-m-s- -i-s- -L-i-s-t-)- -?- -r-a-w-I-t-e-m-s-.-c-a-s-t-<-d-y-n-a-m-i-c->-(-)- -:- -<-d-y-n-a-m-i-c->-[-]-;--
- - - - -f-i-n-a-l- -l-m- -=- -(-r-a-w-M-o-v-e-s- -i-s- -L-i-s-t-)- -?- -r-a-w-M-o-v-e-s-.-c-a-s-t-<-d-y-n-a-m-i-c->-(-)- -:- -<-d-y-n-a-m-i-c->-[-]-;--
--
- - - - -i-n-v-e-n-t-o-r-y-I-t-e-m-s--
- - - - - - -.-.-c-l-e-a-r-(-)--
- - - - - - -.-.-a-d-d-A-l-l-(-l-i-.-w-h-e-r-e-T-y-p-e-<-M-a-p->-(-)-.-m-a-p-(-I-n-v-e-n-t-o-r-y-I-t-e-m-.-f-r-o-m-M-a-p-)-)-;--
--
- - - - -s-t-o-c-k-M-o-v-e-s--
- - - - - - -.-.-c-l-e-a-r-(-)--
- - - - - - -.-.-a-d-d-A-l-l-(-l-m-.-w-h-e-r-e-T-y-p-e-<-M-a-p->-(-)-.-m-a-p-(-S-t-o-c-k-M-o-v-e-.-f-r-o-m-M-a-p-)-)-;--
--
- - - - -n-o-t-i-f-y-L-i-s-t-e-n-e-r-s-(-)-;--
- - -}--
--
- - -v-o-i-d- -_-p-e-r-s-i-s-t-A-l-l-(-)- -{--
- - - - -b-o-x-.-p-u-t-(-"-t-e-n-a-n-t-N-a-m-e-"-,- -t-e-n-a-n-t-N-a-m-e-)-;--
- - - - -b-o-x-.-p-u-t-(-"-b-r-a-n-c-h-N-a-m-e-"-,- -b-r-a-n-c-h-N-a-m-e-)-;--
- - - - -b-o-x-.-p-u-t-(-"-l-o-c-a-l-e-"-,- -l-o-c-a-l-e-)-;--
- - - - -b-o-x-.-p-u-t-(-"-c-u-r-r-e-n-c-y-C-o-d-e-"-,- -c-u-r-r-e-n-c-y-C-o-d-e-)-;--
- - - - -b-o-x-.-p-u-t-(-"-d-e-c-i-m-a-l-S-e-p-"-,- -d-e-c-i-m-a-l-S-e-p-)-;--
- - - - -b-o-x-.-p-u-t-(-"-t-h-o-u-s-a-n-d-S-e-p-"-,- -t-h-o-u-s-a-n-d-S-e-p-)-;--
- - - - -b-o-x-.-p-u-t-(-"-t-a-x-E-n-a-b-l-e-d-"-,- -t-a-x-E-n-a-b-l-e-d-)-;--
- - - - -b-o-x-.-p-u-t-(-"-t-a-x-R-a-t-e-"-,- -t-a-x-R-a-t-e-)-;--
- - - - -b-o-x-.-p-u-t-(-"-t-a-x-M-o-d-e-"-,- -t-a-x-M-o-d-e-)-;--
--
- - - - -b-o-x-.-p-u-t-(-"-t-h-e-m-e-S-c-h-e-m-e-"-,- -t-h-e-m-e-S-c-h-e-m-e-.-n-a-m-e-)-;--
--
- - - - -b-o-x-.-p-u-t-(-"-s-a-l-e-s-"-,- -s-a-l-e-s-)-;--
- - - - -b-o-x-.-p-u-t-(-"-i-n-v-e-n-t-o-r-y-_-i-t-e-m-s-"-,- -i-n-v-e-n-t-o-r-y-I-t-e-m-s-.-m-a-p-(-(-i-)- -=->- -i-.-t-o-M-a-p-(-)-)-.-t-o-L-i-s-t-(-)-)-;--
- - - - -b-o-x-.-p-u-t-(-"-s-t-o-c-k-_-m-o-v-e-s-"-,- -s-t-o-c-k-M-o-v-e-s-.-m-a-p-(-(-m-)- -=->- -m-.-t-o-M-a-p-(-)-)-.-t-o-L-i-s-t-(-)-)-;--
- - -}--
--
- - -v-o-i-d- -s-e-t-C-o-n-f-i-g-(-{--
- - - - -r-e-q-u-i-r-e-d- -S-t-r-i-n-g- -t-e-n-a-n-t-N-a-m-e-,--
- - - - -r-e-q-u-i-r-e-d- -S-t-r-i-n-g- -b-r-a-n-c-h-N-a-m-e-,--
- - - - -r-e-q-u-i-r-e-d- -S-t-r-i-n-g- -l-o-c-a-l-e-,--
- - - - -r-e-q-u-i-r-e-d- -S-t-r-i-n-g- -c-u-r-r-e-n-c-y-C-o-d-e-,--
- - - - -r-e-q-u-i-r-e-d- -S-t-r-i-n-g- -d-e-c-i-m-a-l-S-e-p-,--
- - - - -r-e-q-u-i-r-e-d- -S-t-r-i-n-g- -t-h-o-u-s-a-n-d-S-e-p-,--
- - - - -r-e-q-u-i-r-e-d- -b-o-o-l- -t-a-x-E-n-a-b-l-e-d-,--
- - - - -r-e-q-u-i-r-e-d- -d-o-u-b-l-e- -t-a-x-R-a-t-e-,--
- - - - -r-e-q-u-i-r-e-d- -S-t-r-i-n-g- -t-a-x-M-o-d-e-,--
- - -}-)- -{--
- - - - -t-h-i-s-.-t-e-n-a-n-t-N-a-m-e- -=- -t-e-n-a-n-t-N-a-m-e-;--
- - - - -t-h-i-s-.-b-r-a-n-c-h-N-a-m-e- -=- -b-r-a-n-c-h-N-a-m-e-;--
- - - - -t-h-i-s-.-l-o-c-a-l-e- -=- -l-o-c-a-l-e-;--
- - - - -t-h-i-s-.-c-u-r-r-e-n-c-y-C-o-d-e- -=- -c-u-r-r-e-n-c-y-C-o-d-e-;--
- - - - -t-h-i-s-.-d-e-c-i-m-a-l-S-e-p- -=- -d-e-c-i-m-a-l-S-e-p-;--
- - - - -t-h-i-s-.-t-h-o-u-s-a-n-d-S-e-p- -=- -t-h-o-u-s-a-n-d-S-e-p-;--
- - - - -t-h-i-s-.-t-a-x-E-n-a-b-l-e-d- -=- -t-a-x-E-n-a-b-l-e-d-;--
- - - - -t-h-i-s-.-t-a-x-R-a-t-e- -=- -t-a-x-R-a-t-e-;--
- - - - -t-h-i-s-.-t-a-x-M-o-d-e- -=- -t-a-x-M-o-d-e-;--
- - - - -_-p-e-r-s-i-s-t-A-l-l-(-)-;--
- - - - -n-o-t-i-f-y-L-i-s-t-e-n-e-r-s-(-)-;--
- - -}--
--
- - -v-o-i-d- -s-e-t-T-h-e-m-e-S-c-h-e-m-e-(-T-h-e-m-e-S-c-h-e-m-e- -s-c-h-e-m-e-)- -{--
- - - - -t-h-e-m-e-S-c-h-e-m-e- -=- -s-c-h-e-m-e-;--
- - - - -_-p-e-r-s-i-s-t-A-l-l-(-)-;--
- - - - -n-o-t-i-f-y-L-i-s-t-e-n-e-r-s-(-)-;--
- - -}--
--
- - -/-/- -=-=-=-=-=- -V-e-n-t-a-s--
- - -v-o-i-d- -a-d-d-S-a-l-e-(-{-r-e-q-u-i-r-e-d- -d-o-u-b-l-e- -a-m-o-u-n-t-,- -S-t-r-i-n-g- -m-e-t-h-o-d- -=- -"-E-f-e-c-t-i-v-o-"-,- -S-t-r-i-n-g- -t-y-p-e- -=- -"-M-a-n-u-a-l-"-}-)- -{--
- - - - -a-d-d-S-a-l-e-A-t-(-t-s-:- -D-a-t-e-T-i-m-e-.-n-o-w-(-)-,- -a-m-o-u-n-t-:- -a-m-o-u-n-t-,- -m-e-t-h-o-d-:- -m-e-t-h-o-d-,- -t-y-p-e-:- -t-y-p-e-)-;--
- - -}--
--
- - -v-o-i-d- -a-d-d-S-a-l-e-A-t-(-{--
- - - - -r-e-q-u-i-r-e-d- -D-a-t-e-T-i-m-e- -t-s-,--
- - - - -r-e-q-u-i-r-e-d- -d-o-u-b-l-e- -a-m-o-u-n-t-,--
- - - - -S-t-r-i-n-g- -m-e-t-h-o-d- -=- -"-E-f-e-c-t-i-v-o-"-,--
- - - - -S-t-r-i-n-g- -t-y-p-e- -=- -"-I-m-p-o-r-t-"-,--
- - -}-)- -{--
- - - - -s-a-l-e-s-.-i-n-s-e-r-t-(-0-,- -{--
- - - - - - -"-i-d-"-:- -"-s-_-$-{-D-a-t-e-T-i-m-e-.-n-o-w-(-)-.-m-i-l-l-i-s-e-c-o-n-d-s-S-i-n-c-e-E-p-o-c-h-}-"-,--
- - - - - - -"-t-s-"-:- -t-s-.-t-o-I-s-o-8-6-0-1-S-t-r-i-n-g-(-)-,--
- - - - - - -"-a-m-o-u-n-t-"-:- -a-m-o-u-n-t-,--
- - - - - - -"-m-e-t-h-o-d-"-:- -m-e-t-h-o-d-,--
- - - - - - -"-t-y-p-e-"-:- -t-y-p-e-,--
- - - - -}-)-;--
- - - - -_-p-e-r-s-i-s-t-A-l-l-(-)-;--
- - - - -n-o-t-i-f-y-L-i-s-t-e-n-e-r-s-(-)-;--
- - -}--
--
- - -v-o-i-d- -a-d-d-Q-u-i-c-k-S-a-l-e-(-{-r-e-q-u-i-r-e-d- -d-o-u-b-l-e- -a-m-o-u-n-t-,- -S-t-r-i-n-g- -m-e-t-h-o-d- -=- -"-E-f-e-c-t-i-v-o-"-}-)- -{--
- - - - -a-d-d-S-a-l-e-(-a-m-o-u-n-t-:- -a-m-o-u-n-t-,- -m-e-t-h-o-d-:- -m-e-t-h-o-d-,- -t-y-p-e-:- -"-R-Ã-¡-p-i-d-a-"-)-;--
- - -}--
--
- - -d-o-u-b-l-e- -g-e-t- -t-o-d-a-y-S-a-l-e-s-T-o-t-a-l- -{--
- - - - -f-i-n-a-l- -n-o-w- -=- -D-a-t-e-T-i-m-e-.-n-o-w-(-)-;--
- - - - -d-o-u-b-l-e- -s-u-m- -=- -0-;--
- - - - -f-o-r- -(-f-i-n-a-l- -s- -i-n- -s-a-l-e-s-)- -{--
- - - - - - -f-i-n-a-l- -t-s- -=- -D-a-t-e-T-i-m-e-.-t-r-y-P-a-r-s-e-(-(-s-[-"-t-s-"-]- -?-?- -"-"-)-.-t-o-S-t-r-i-n-g-(-)-)-;--
- - - - - - -i-f- -(-t-s- -=-=- -n-u-l-l-)- -c-o-n-t-i-n-u-e-;--
- - - - - - -i-f- -(-t-s-.-y-e-a-r- -=-=- -n-o-w-.-y-e-a-r- -&-&- -t-s-.-m-o-n-t-h- -=-=- -n-o-w-.-m-o-n-t-h- -&-&- -t-s-.-d-a-y- -=-=- -n-o-w-.-d-a-y-)- -{--
- - - - - - - - -s-u-m- -+-=- -(-(-s-[-"-a-m-o-u-n-t-"-]- -?-?- -0-)- -a-s- -n-u-m-)-.-t-o-D-o-u-b-l-e-(-)-;--
- - - - - - -}--
- - - - -}--
- - - - -r-e-t-u-r-n- -s-u-m-;--
- - -}--
--
- - -i-n-t- -g-e-t- -t-o-d-a-y-O-r-d-e-r-s-C-o-u-n-t- -{--
- - - - -f-i-n-a-l- -n-o-w- -=- -D-a-t-e-T-i-m-e-.-n-o-w-(-)-;--
- - - - -i-n-t- -c- -=- -0-;--
- - - - -f-o-r- -(-f-i-n-a-l- -s- -i-n- -s-a-l-e-s-)- -{--
- - - - - - -f-i-n-a-l- -t-s- -=- -D-a-t-e-T-i-m-e-.-t-r-y-P-a-r-s-e-(-(-s-[-"-t-s-"-]- -?-?- -"-"-)-.-t-o-S-t-r-i-n-g-(-)-)-;--
- - - - - - -i-f- -(-t-s- -=-=- -n-u-l-l-)- -c-o-n-t-i-n-u-e-;--
- - - - - - -i-f- -(-t-s-.-y-e-a-r- -=-=- -n-o-w-.-y-e-a-r- -&-&- -t-s-.-m-o-n-t-h- -=-=- -n-o-w-.-m-o-n-t-h- -&-&- -t-s-.-d-a-y- -=-=- -n-o-w-.-d-a-y-)- -c-+-+-;--
- - - - -}--
- - - - -r-e-t-u-r-n- -c-;--
- - -}--
--
- - -/-/- -=-=-=-=-=- -I-n-v-e-n-t-a-r-i-o--
- - -v-o-i-d- -a-d-d-I-n-v-e-n-t-o-r-y-I-t-e-m-(-I-n-v-e-n-t-o-r-y-I-t-e-m- -i-t-e-m-)- -{--
- - - - -i-n-v-e-n-t-o-r-y-I-t-e-m-s-.-a-d-d-(-i-t-e-m-)-;--
- - - - -_-p-e-r-s-i-s-t-A-l-l-(-)-;--
- - - - -n-o-t-i-f-y-L-i-s-t-e-n-e-r-s-(-)-;--
- - -}--
--
- - -v-o-i-d- -a-d-d-S-t-o-c-k-M-o-v-e-(-S-t-o-c-k-M-o-v-e- -m-o-v-e-)- -{--
- - - - -s-t-o-c-k-M-o-v-e-s-.-a-d-d-(-m-o-v-e-)-;--
- - - - -_-p-e-r-s-i-s-t-A-l-l-(-)-;--
- - - - -n-o-t-i-f-y-L-i-s-t-e-n-e-r-s-(-)-;--
- - -}--
--
- - -d-o-u-b-l-e- -s-t-o-c-k-O-f-(-S-t-r-i-n-g- -i-t-e-m-I-d-)- -{--
- - - - -d-o-u-b-l-e- -s-t-o-c-k- -=- -0-.-0-;--
- - - - -f-o-r- -(-f-i-n-a-l- -m- -i-n- -s-t-o-c-k-M-o-v-e-s-.-w-h-e-r-e-(-(-x-)- -=->- -x-.-i-t-e-m-I-d- -=-=- -i-t-e-m-I-d-)-)- -{--
- - - - - - -i-f- -(-m-.-t-y-p-e- -=-=- -M-o-v-e-T-y-p-e-.-i-n-M-o-v-e-)- -s-t-o-c-k- -+-=- -m-.-q-t-y-;--
- - - - - - -i-f- -(-m-.-t-y-p-e- -=-=- -M-o-v-e-T-y-p-e-.-o-u-t-M-o-v-e-)- -s-t-o-c-k- ---=- -m-.-q-t-y-;--
- - - - - - -i-f- -(-m-.-t-y-p-e- -=-=- -M-o-v-e-T-y-p-e-.-a-d-j-u-s-t-)- -s-t-o-c-k- -=- -m-.-q-t-y-;--
- - - - -}--
- - - - -r-e-t-u-r-n- -s-t-o-c-k-;--
- - -}--
--
- - -b-o-o-l- -g-e-t- -h-a-s-L-o-w-S-t-o-c-k- -{--
- - - - -f-o-r- -(-f-i-n-a-l- -i-t- -i-n- -i-n-v-e-n-t-o-r-y-I-t-e-m-s-)- -{--
- - - - - - -i-f- -(-i-t-.-s-t-o-c-k-P-o-l-i-c-y- -=-=- -S-t-o-c-k-P-o-l-i-c-y-.-t-r-a-c-k-e-d-)- -{--
- - - - - - - - -i-f- -(-s-t-o-c-k-O-f-(-i-t-.-i-d-)- -<- -i-t-.-m-i-n-S-t-o-c-k-)- -r-e-t-u-r-n- -t-r-u-e-;--
- - - - - - -}--
- - - - -}--
- - - - -r-e-t-u-r-n- -f-a-l-s-e-;--
- - -}--
--
- - -v-o-i-d- -s-y-n-c-N-o-w-(-)- -{--
- - - - -n-o-t-i-f-y-L-i-s-t-e-n-e-r-s-(-)-;--
- - -}--
-}--
--
-c-l-a-s-s- -A-p-p-S-t-a-t-e-S-c-o-p-e- -e-x-t-e-n-d-s- -I-n-h-e-r-i-t-e-d-N-o-t-i-f-i-e-r-<-A-p-p-S-t-a-t-e->- -{--
- - -c-o-n-s-t- -A-p-p-S-t-a-t-e-S-c-o-p-e-(-{-s-u-p-e-r-.-k-e-y-,- -r-e-q-u-i-r-e-d- -A-p-p-S-t-a-t-e- -n-o-t-i-f-i-e-r-,- -r-e-q-u-i-r-e-d- -W-i-d-g-e-t- -c-h-i-l-d-}-)--
- - - - - - -:- -s-u-p-e-r-(-n-o-t-i-f-i-e-r-:- -n-o-t-i-f-i-e-r-,- -c-h-i-l-d-:- -c-h-i-l-d-)-;--
--
- - -s-t-a-t-i-c- -A-p-p-S-t-a-t-e- -o-f-(-B-u-i-l-d-C-o-n-t-e-x-t- -c-o-n-t-e-x-t-)- -=->--
- - - - - - -c-o-n-t-e-x-t-.-d-e-p-e-n-d-O-n-I-n-h-e-r-i-t-e-d-W-i-d-g-e-t-O-f-E-x-a-c-t-T-y-p-e-<-A-p-p-S-t-a-t-e-S-c-o-p-e->-(-)-!-.-n-o-t-i-f-i-e-r-!-;--
-}--
--
-c-l-a-s-s- -R-a-u-l-i-A-p-p- -e-x-t-e-n-d-s- -S-t-a-t-e-l-e-s-s-W-i-d-g-e-t- -{--
- - -c-o-n-s-t- -R-a-u-l-i-A-p-p-(-{-s-u-p-e-r-.-k-e-y-}-)-;--
--
- - -@-o-v-e-r-r-i-d-e--
- - -W-i-d-g-e-t- -b-u-i-l-d-(-B-u-i-l-d-C-o-n-t-e-x-t- -c-o-n-t-e-x-t-)- -{--
- - - - -f-i-n-a-l- -s-t-a-t-e- -=- -A-p-p-S-t-a-t-e-S-c-o-p-e-.-o-f-(-c-o-n-t-e-x-t-)-;--
- - - - -r-e-t-u-r-n- -M-a-t-e-r-i-a-l-A-p-p-(--
- - - - - - -d-e-b-u-g-S-h-o-w-C-h-e-c-k-e-d-M-o-d-e-B-a-n-n-e-r-:- -f-a-l-s-e-,--
- - - - - - -t-i-t-l-e-:- -"-R-A-U-L-I-"-,--
- - - - - - -t-h-e-m-e-:- -R-a-u-l-i-T-h-e-m-e-.-b-u-i-l-d-(-s-t-a-t-e-.-t-h-e-m-e-S-c-h-e-m-e-)-,--
- - - - - - -h-o-m-e-:- -c-o-n-s-t- -A-p-p-S-h-e-l-l-(-)-,--
- - - - -)-;--
- - -}--
-}--
--
-c-l-a-s-s- -A-p-p-S-h-e-l-l- -e-x-t-e-n-d-s- -S-t-a-t-e-f-u-l-W-i-d-g-e-t- -{--
- - -c-o-n-s-t- -A-p-p-S-h-e-l-l-(-{-s-u-p-e-r-.-k-e-y-}-)-;--
--
- - -@-o-v-e-r-r-i-d-e--
- - -S-t-a-t-e-<-A-p-p-S-h-e-l-l->- -c-r-e-a-t-e-S-t-a-t-e-(-)- -=->- -_-A-p-p-S-h-e-l-l-S-t-a-t-e-(-)-;--
-}--
--
-c-l-a-s-s- -_-A-p-p-S-h-e-l-l-S-t-a-t-e- -e-x-t-e-n-d-s- -S-t-a-t-e-<-A-p-p-S-h-e-l-l->- -{--
- - -i-n-t- -i-n-d-e-x- -=- -0-;--
--
- - -@-o-v-e-r-r-i-d-e--
- - -W-i-d-g-e-t- -b-u-i-l-d-(-B-u-i-l-d-C-o-n-t-e-x-t- -c-o-n-t-e-x-t-)- -{--
- - - - -f-i-n-a-l- -s-t-a-t-e- -=- -A-p-p-S-t-a-t-e-S-c-o-p-e-.-o-f-(-c-o-n-t-e-x-t-)-;--
--
- - - - -f-i-n-a-l- -p-a-g-e-s- -=- -<-W-i-d-g-e-t->-[--
- - - - - - -_-D-a-s-h-b-o-a-r-d-(-o-n-Q-u-i-c-k-S-a-l-e-:- -(-)- -=->- -s-t-a-t-e-.-a-d-d-Q-u-i-c-k-S-a-l-e-(-a-m-o-u-n-t-:- -1-0-0-)-)-,--
- - - - - - -c-o-n-s-t- -S-a-l-e-s-S-c-r-e-e-n-P-r-o-(-)-,--
- - - - - - -c-o-n-s-t- -_-P-r-o-d-u-c-t-i-o-n-S-c-r-e-e-n-(-)-,--
- - - - - - -c-o-n-s-t- -I-n-v-e-n-t-o-r-y-S-c-r-e-e-n-P-r-o-(-)-,--
- - - - - - -c-o-n-s-t- -S-e-t-t-i-n-g-s-S-c-r-e-e-n-(-)-,--
- - - - -]-;--
--
- - - - -r-e-t-u-r-n- -S-c-a-f-f-o-l-d-(--
- - - - - - -a-p-p-B-a-r-:- -A-p-p-B-a-r-(--
- - - - - - - - -t-i-t-l-e-:- -c-o-n-s-t- -T-e-x-t-(-"-R-A-U-L-I- -â-€-“- -N-e-g-o-c-i-o-"-)-,--
- - - - - - - - -a-c-t-i-o-n-s-:- -[--
- - - - - - - - - - -I-c-o-n-B-u-t-t-o-n-(--
- - - - - - - - - - - - -t-o-o-l-t-i-p-:- -"-I-A- -(-p-r-Ã-³-x-i-m-o-)-"-,--
- - - - - - - - - - - - -o-n-P-r-e-s-s-e-d-:- -(-)- -{--
- - - - - - - - - - - - - - -S-c-a-f-f-o-l-d-M-e-s-s-e-n-g-e-r-.-o-f-(-c-o-n-t-e-x-t-)-.-s-h-o-w-S-n-a-c-k-B-a-r-(--
- - - - - - - - - - - - - - - - -c-o-n-s-t- -S-n-a-c-k-B-a-r-(-c-o-n-t-e-n-t-:- -T-e-x-t-(-"-I-A- -R-A-U-L-I-:- -v-o-z- -+- -s-o-p-o-r-t-e- -+- -t-i-c-k-e-t-s- -(-p-r-Ã-³-x-i-m-o-)-.-"-)-)-,--
- - - - - - - - - - - - - - -)-;--
- - - - - - - - - - - - -}-,--
- - - - - - - - - - - - -i-c-o-n-:- -c-o-n-s-t- -I-c-o-n-(-I-c-o-n-s-.-m-i-c-_-r-o-u-n-d-e-d-)-,--
- - - - - - - - - - -)-,--
- - - - - - - - - - -I-c-o-n-B-u-t-t-o-n-(--
- - - - - - - - - - - - -t-o-o-l-t-i-p-:- -"-A-c-t-u-a-l-i-z-a-r- -/- -S-i-n-c-r-o-n-i-z-a-r-"-,--
- - - - - - - - - - - - -o-n-P-r-e-s-s-e-d-:- -(-)- -{--
- - - - - - - - - - - - - - -s-t-a-t-e-.-s-y-n-c-N-o-w-(-)-;--
- - - - - - - - - - - - - - -S-c-a-f-f-o-l-d-M-e-s-s-e-n-g-e-r-.-o-f-(-c-o-n-t-e-x-t-)-.-s-h-o-w-S-n-a-c-k-B-a-r-(--
- - - - - - - - - - - - - - - - -c-o-n-s-t- -S-n-a-c-k-B-a-r-(-c-o-n-t-e-n-t-:- -T-e-x-t-(-"-A-c-t-u-a-l-i-z-a-c-i-Ã-³-n- -e-j-e-c-u-t-a-d-a- -(-o-f-f-l-i-n-e-)-.-"-)-)-,--
- - - - - - - - - - - - - - -)-;--
- - - - - - - - - - - - -}-,--
- - - - - - - - - - - - -i-c-o-n-:- -c-o-n-s-t- -I-c-o-n-(-I-c-o-n-s-.-r-e-f-r-e-s-h-_-r-o-u-n-d-e-d-)-,--
- - - - - - - - - - -)-,--
- - - - - - - - - - -I-c-o-n-B-u-t-t-o-n-(--
- - - - - - - - - - - - -t-o-o-l-t-i-p-:- -"-C-o-n-f-i-g-u-r-a-c-i-Ã-³-n-"-,--
- - - - - - - - - - - - -o-n-P-r-e-s-s-e-d-:- -(-)- -=->- -s-e-t-S-t-a-t-e-(-(-)- -=->- -i-n-d-e-x- -=- -4-)-,--
- - - - - - - - - - - - -i-c-o-n-:- -c-o-n-s-t- -I-c-o-n-(-I-c-o-n-s-.-s-e-t-t-i-n-g-s-_-r-o-u-n-d-e-d-)-,--
- - - - - - - - - - -)-,--
- - - - - - - - - - -c-o-n-s-t- -S-i-z-e-d-B-o-x-(-w-i-d-t-h-:- -6-)-,--
- - - - - - - - -]-,--
- - - - - - -)-,--
- - - - - - -b-o-d-y-:- -p-a-g-e-s-[-i-n-d-e-x-]-,--
- - - - - - -b-o-t-t-o-m-N-a-v-i-g-a-t-i-o-n-B-a-r-:- -N-a-v-i-g-a-t-i-o-n-B-a-r-(--
- - - - - - - - -s-e-l-e-c-t-e-d-I-n-d-e-x-:- -i-n-d-e-x-,--
- - - - - - - - -o-n-D-e-s-t-i-n-a-t-i-o-n-S-e-l-e-c-t-e-d-:- -(-v-)- -=->- -s-e-t-S-t-a-t-e-(-(-)- -=->- -i-n-d-e-x- -=- -v-)-,--
- - - - - - - - -d-e-s-t-i-n-a-t-i-o-n-s-:- -[--
- - - - - - - - - - -c-o-n-s-t- -N-a-v-i-g-a-t-i-o-n-D-e-s-t-i-n-a-t-i-o-n-(-i-c-o-n-:- -I-c-o-n-(-I-c-o-n-s-.-d-a-s-h-b-o-a-r-d-_-r-o-u-n-d-e-d-)-,- -l-a-b-e-l-:- -"-D-a-s-h-b-o-a-r-d-"-)-,--
- - - - - - - - - - -c-o-n-s-t- -N-a-v-i-g-a-t-i-o-n-D-e-s-t-i-n-a-t-i-o-n-(-i-c-o-n-:- -I-c-o-n-(-I-c-o-n-s-.-p-o-i-n-t-_-o-f-_-s-a-l-e-_-r-o-u-n-d-e-d-)-,- -l-a-b-e-l-:- -"-V-e-n-t-a-s-"-)-,--
- - - - - - - - - - -c-o-n-s-t- -N-a-v-i-g-a-t-i-o-n-D-e-s-t-i-n-a-t-i-o-n-(-i-c-o-n-:- -I-c-o-n-(-I-c-o-n-s-.-f-a-c-t-o-r-y-_-r-o-u-n-d-e-d-)-,- -l-a-b-e-l-:- -"-P-r-o-d-u-c-c-i-Ã-³-n-"-)-,--
- - - - - - - - - - -N-a-v-i-g-a-t-i-o-n-D-e-s-t-i-n-a-t-i-o-n-(--
- - - - - - - - - - - - -i-c-o-n-:- -S-t-a-c-k-(--
- - - - - - - - - - - - - - -c-h-i-l-d-r-e-n-:- -[--
- - - - - - - - - - - - - - - - -c-o-n-s-t- -I-c-o-n-(-I-c-o-n-s-.-i-n-v-e-n-t-o-r-y-_-2-_-r-o-u-n-d-e-d-)-,--
- - - - - - - - - - - - - - - - -i-f- -(-s-t-a-t-e-.-h-a-s-L-o-w-S-t-o-c-k-)--
- - - - - - - - - - - - - - - - - - -P-o-s-i-t-i-o-n-e-d-(--
- - - - - - - - - - - - - - - - - - - - -r-i-g-h-t-:- -0-,--
- - - - - - - - - - - - - - - - - - - - -t-o-p-:- -0-,--
- - - - - - - - - - - - - - - - - - - - -c-h-i-l-d-:- -C-o-n-t-a-i-n-e-r-(--
- - - - - - - - - - - - - - - - - - - - - - -w-i-d-t-h-:- -1-0-,--
- - - - - - - - - - - - - - - - - - - - - - -h-e-i-g-h-t-:- -1-0-,--
- - - - - - - - - - - - - - - - - - - - - - -d-e-c-o-r-a-t-i-o-n-:- -B-o-x-D-e-c-o-r-a-t-i-o-n-(--
- - - - - - - - - - - - - - - - - - - - - - - - -c-o-l-o-r-:- -C-o-l-o-r-s-.-r-e-d-,--
- - - - - - - - - - - - - - - - - - - - - - - - -b-o-r-d-e-r-R-a-d-i-u-s-:- -B-o-r-d-e-r-R-a-d-i-u-s-.-c-i-r-c-u-l-a-r-(-9-9-)-,--
- - - - - - - - - - - - - - - - - - - - - - -)-,--
- - - - - - - - - - - - - - - - - - - - -)-,--
- - - - - - - - - - - - - - - - - - -)-,--
- - - - - - - - - - - - - - -]-,--
- - - - - - - - - - - - -)-,--
- - - - - - - - - - - - -l-a-b-e-l-:- -"-I-n-v-e-n-t-a-r-i-o-"-,--
- - - - - - - - - - -)-,--
- - - - - - - - - - -c-o-n-s-t- -N-a-v-i-g-a-t-i-o-n-D-e-s-t-i-n-a-t-i-o-n-(-i-c-o-n-:- -I-c-o-n-(-I-c-o-n-s-.-s-e-t-t-i-n-g-s-_-r-o-u-n-d-e-d-)-,- -l-a-b-e-l-:- -"-C-o-n-f-i-g-"-)-,--
- - - - - - - - -]-,--
- - - - - - -)-,--
- - - - -)-;--
- - -}--
-}--
--
-c-l-a-s-s- -_-D-a-s-h-b-o-a-r-d- -e-x-t-e-n-d-s- -S-t-a-t-e-l-e-s-s-W-i-d-g-e-t- -{--
- - -f-i-n-a-l- -V-o-i-d-C-a-l-l-b-a-c-k- -o-n-Q-u-i-c-k-S-a-l-e-;--
- - -c-o-n-s-t- -_-D-a-s-h-b-o-a-r-d-(-{-r-e-q-u-i-r-e-d- -t-h-i-s-.-o-n-Q-u-i-c-k-S-a-l-e-}-)-;--
--
- - -@-o-v-e-r-r-i-d-e--
- - -W-i-d-g-e-t- -b-u-i-l-d-(-B-u-i-l-d-C-o-n-t-e-x-t- -c-o-n-t-e-x-t-)- -{--
- - - - -f-i-n-a-l- -s-t-a-t-e- -=- -A-p-p-S-t-a-t-e-S-c-o-p-e-.-o-f-(-c-o-n-t-e-x-t-)-;--
--
- - - - -r-e-t-u-r-n- -S-i-n-g-l-e-C-h-i-l-d-S-c-r-o-l-l-V-i-e-w-(--
- - - - - - -p-a-d-d-i-n-g-:- -c-o-n-s-t- -E-d-g-e-I-n-s-e-t-s-.-a-l-l-(-1-6-)-,--
- - - - - - -c-h-i-l-d-:- -C-o-n-s-t-r-a-i-n-e-d-B-o-x-(--
- - - - - - - - -c-o-n-s-t-r-a-i-n-t-s-:- -c-o-n-s-t- -B-o-x-C-o-n-s-t-r-a-i-n-t-s-(-m-a-x-W-i-d-t-h-:- -1-0-4-0-)-,--
- - - - - - - - -c-h-i-l-d-:- -C-o-l-u-m-n-(--
- - - - - - - - - - -c-r-o-s-s-A-x-i-s-A-l-i-g-n-m-e-n-t-:- -C-r-o-s-s-A-x-i-s-A-l-i-g-n-m-e-n-t-.-s-t-a-r-t-,--
- - - - - - - - - - -c-h-i-l-d-r-e-n-:- -[--
- - - - - - - - - - - - -C-a-r-d-(--
- - - - - - - - - - - - - - -c-h-i-l-d-:- -P-a-d-d-i-n-g-(--
- - - - - - - - - - - - - - - - -p-a-d-d-i-n-g-:- -c-o-n-s-t- -E-d-g-e-I-n-s-e-t-s-.-a-l-l-(-1-6-)-,--
- - - - - - - - - - - - - - - - -c-h-i-l-d-:- -R-o-w-(--
- - - - - - - - - - - - - - - - - - -c-h-i-l-d-r-e-n-:- -[--
- - - - - - - - - - - - - - - - - - - - -E-x-p-a-n-d-e-d-(--
- - - - - - - - - - - - - - - - - - - - - - -c-h-i-l-d-:- -C-o-l-u-m-n-(--
- - - - - - - - - - - - - - - - - - - - - - - - -c-r-o-s-s-A-x-i-s-A-l-i-g-n-m-e-n-t-:- -C-r-o-s-s-A-x-i-s-A-l-i-g-n-m-e-n-t-.-s-t-a-r-t-,--
- - - - - - - - - - - - - - - - - - - - - - - - -c-h-i-l-d-r-e-n-:- -[--
- - - - - - - - - - - - - - - - - - - - - - - - - - -c-o-n-s-t- -T-e-x-t-(-"-D-a-s-h-b-o-a-r-d-"-,--
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -s-t-y-l-e-:- -T-e-x-t-S-t-y-l-e-(-f-o-n-t-S-i-z-e-:- -2-0-,- -f-o-n-t-W-e-i-g-h-t-:- -F-o-n-t-W-e-i-g-h-t-.-w-9-0-0-)-)-,--
- - - - - - - - - - - - - - - - - - - - - - - - - - -c-o-n-s-t- -S-i-z-e-d-B-o-x-(-h-e-i-g-h-t-:- -4-)-,--
- - - - - - - - - - - - - - - - - - - - - - - - - - -T-e-x-t-(--
- - - - - - - - - - - - - - - - - - - - - - - - - - - - -"-$-{-s-t-a-t-e-.-b-r-a-n-c-h-N-a-m-e-}- -â-€-¢- -O-f-f-l-i-n-e---F-i-r-s-t- -â-€-¢- -$-{-s-t-a-t-e-.-c-u-r-r-e-n-c-y-C-o-d-e-}-"-,--
- - - - - - - - - - - - - - - - - - - - - - - - - - - - -s-t-y-l-e-:- -c-o-n-s-t- -T-e-x-t-S-t-y-l-e-(-c-o-l-o-r-:- -C-o-l-o-r-s-.-b-l-a-c-k-5-4-)-,--
- - - - - - - - - - - - - - - - - - - - - - - - - - -)-,--
- - - - - - - - - - - - - - - - - - - - - - - - -]-,--
- - - - - - - - - - - - - - - - - - - - - - -)-,--
- - - - - - - - - - - - - - - - - - - - -)-,--
- - - - - - - - - - - - - - - - - - - - -F-i-l-l-e-d-B-u-t-t-o-n-.-t-o-n-a-l-I-c-o-n-(--
- - - - - - - - - - - - - - - - - - - - - - -o-n-P-r-e-s-s-e-d-:- -(-)- -{--
- - - - - - - - - - - - - - - - - - - - - - - - -s-t-a-t-e-.-s-y-n-c-N-o-w-(-)-;--
- - - - - - - - - - - - - - - - - - - - - - - - -S-c-a-f-f-o-l-d-M-e-s-s-e-n-g-e-r-.-o-f-(-c-o-n-t-e-x-t-)-.-s-h-o-w-S-n-a-c-k-B-a-r-(--
- - - - - - - - - - - - - - - - - - - - - - - - - - -c-o-n-s-t- -S-n-a-c-k-B-a-r-(-c-o-n-t-e-n-t-:- -T-e-x-t-(-"-A-c-t-u-a-l-i-z-a-c-i-Ã-³-n- -e-j-e-c-u-t-a-d-a-.-"-)-)-,--
- - - - - - - - - - - - - - - - - - - - - - - - -)-;--
- - - - - - - - - - - - - - - - - - - - - - -}-,--
- - - - - - - - - - - - - - - - - - - - - - -i-c-o-n-:- -c-o-n-s-t- -I-c-o-n-(-I-c-o-n-s-.-r-e-f-r-e-s-h-_-r-o-u-n-d-e-d-)-,--
- - - - - - - - - - - - - - - - - - - - - - -l-a-b-e-l-:- -c-o-n-s-t- -T-e-x-t-(-"-A-c-t-u-a-l-i-z-a-r-"-)-,--
- - - - - - - - - - - - - - - - - - - - -)-,--
- - - - - - - - - - - - - - - - - - -]-,--
- - - - - - - - - - - - - - - - -)-,--
- - - - - - - - - - - - - - -)-,--
- - - - - - - - - - - - -)-,--
- - - - - - - - - - - - -c-o-n-s-t- -S-i-z-e-d-B-o-x-(-h-e-i-g-h-t-:- -1-4-)-,--
--
- - - - - - - - - - - - -W-r-a-p-(--
- - - - - - - - - - - - - - -s-p-a-c-i-n-g-:- -1-2-,--
- - - - - - - - - - - - - - -r-u-n-S-p-a-c-i-n-g-:- -1-2-,--
- - - - - - - - - - - - - - -c-h-i-l-d-r-e-n-:- -[--
- - - - - - - - - - - - - - - - -_-S-t-a-t-C-a-r-d-(--
- - - - - - - - - - - - - - - - - - -t-i-t-l-e-:- -"-V-e-n-t-a-s- -H-o-y-"-,--
- - - - - - - - - - - - - - - - - - -v-a-l-u-e-:- -"-\-$- -$-{-s-t-a-t-e-.-t-o-d-a-y-S-a-l-e-s-T-o-t-a-l-.-t-o-S-t-r-i-n-g-A-s-F-i-x-e-d-(-2-)-}-"-,--
- - - - - - - - - - - - - - - - - - -i-c-o-n-:- -I-c-o-n-s-.-a-t-t-a-c-h-_-m-o-n-e-y-_-r-o-u-n-d-e-d-,--
- - - - - - - - - - - - - - - - -)-,--
- - - - - - - - - - - - - - - - -_-S-t-a-t-C-a-r-d-(--
- - - - - - - - - - - - - - - - - - -t-i-t-l-e-:- -"-Ã-“-r-d-e-n-e-s-"-,--
- - - - - - - - - - - - - - - - - - -v-a-l-u-e-:- -"-$-{-s-t-a-t-e-.-t-o-d-a-y-O-r-d-e-r-s-C-o-u-n-t-}-"-,--
- - - - - - - - - - - - - - - - - - -i-c-o-n-:- -I-c-o-n-s-.-r-e-c-e-i-p-t-_-l-o-n-g-_-r-o-u-n-d-e-d-,--
- - - - - - - - - - - - - - - - -)-,--
- - - - - - - - - - - - - - - - -_-S-t-a-t-C-a-r-d-(--
- - - - - - - - - - - - - - - - - - -t-i-t-l-e-:- -"-C-a-j-a-"-,--
- - - - - - - - - - - - - - - - - - -v-a-l-u-e-:- -"-\-$- -$-{-s-t-a-t-e-.-t-o-d-a-y-S-a-l-e-s-T-o-t-a-l-.-t-o-S-t-r-i-n-g-A-s-F-i-x-e-d-(-2-)-}-"-,--
- - - - - - - - - - - - - - - - - - -i-c-o-n-:- -I-c-o-n-s-.-a-c-c-o-u-n-t-_-b-a-l-a-n-c-e-_-w-a-l-l-e-t-_-r-o-u-n-d-e-d-,--
- - - - - - - - - - - - - - - - -)-,--
- - - - - - - - - - - - - - - - -_-S-t-a-t-C-a-r-d-(--
- - - - - - - - - - - - - - - - - - -t-i-t-l-e-:- -"-I-n-v-e-n-t-a-r-i-o-"-,--
- - - - - - - - - - - - - - - - - - -v-a-l-u-e-:- -s-t-a-t-e-.-h-a-s-L-o-w-S-t-o-c-k- -?- -"-L-O-W-"- -:- -"-O-K-"-,--
- - - - - - - - - - - - - - - - - - -i-c-o-n-:- -I-c-o-n-s-.-i-n-v-e-n-t-o-r-y-_-2-_-r-o-u-n-d-e-d-,--
- - - - - - - - - - - - - - - - -)-,--
- - - - - - - - - - - - - - -]-,--
- - - - - - - - - - - - -)-,--
--
- - - - - - - - - - - - -c-o-n-s-t- -S-i-z-e-d-B-o-x-(-h-e-i-g-h-t-:- -1-4-)-,--
--
- - - - - - - - - - - - -C-a-r-d-(--
- - - - - - - - - - - - - - -c-h-i-l-d-:- -P-a-d-d-i-n-g-(--
- - - - - - - - - - - - - - - - -p-a-d-d-i-n-g-:- -c-o-n-s-t- -E-d-g-e-I-n-s-e-t-s-.-a-l-l-(-1-6-)-,--
- - - - - - - - - - - - - - - - -c-h-i-l-d-:- -C-o-l-u-m-n-(-c-r-o-s-s-A-x-i-s-A-l-i-g-n-m-e-n-t-:- -C-r-o-s-s-A-x-i-s-A-l-i-g-n-m-e-n-t-.-s-t-a-r-t-,- -c-h-i-l-d-r-e-n-:- -[--
- - - - - - - - - - - - - - - - - - -c-o-n-s-t- -T-e-x-t-(-"-A-c-c-i-o-n-e-s-"-,- -s-t-y-l-e-:- -T-e-x-t-S-t-y-l-e-(-f-o-n-t-W-e-i-g-h-t-:- -F-o-n-t-W-e-i-g-h-t-.-w-9-0-0-)-)-,--
- - - - - - - - - - - - - - - - - - -c-o-n-s-t- -S-i-z-e-d-B-o-x-(-h-e-i-g-h-t-:- -1-0-)-,--
- - - - - - - - - - - - - - - - - - -W-r-a-p-(--
- - - - - - - - - - - - - - - - - - - - -s-p-a-c-i-n-g-:- -1-2-,--
- - - - - - - - - - - - - - - - - - - - -r-u-n-S-p-a-c-i-n-g-:- -1-2-,--
- - - - - - - - - - - - - - - - - - - - -c-h-i-l-d-r-e-n-:- -[--
- - - - - - - - - - - - - - - - - - - - - - -F-i-l-l-e-d-B-u-t-t-o-n-.-i-c-o-n-(--
- - - - - - - - - - - - - - - - - - - - - - - - -o-n-P-r-e-s-s-e-d-:- -o-n-Q-u-i-c-k-S-a-l-e-,--
- - - - - - - - - - - - - - - - - - - - - - - - -i-c-o-n-:- -c-o-n-s-t- -I-c-o-n-(-I-c-o-n-s-.-f-l-a-s-h-_-o-n-_-r-o-u-n-d-e-d-)-,--
- - - - - - - - - - - - - - - - - - - - - - - - -l-a-b-e-l-:- -c-o-n-s-t- -T-e-x-t-(-"-V-e-n-t-a- -r-Ã-¡-p-i-d-a- -\-$-1-0-0-"-)-,--
- - - - - - - - - - - - - - - - - - - - - - -)-,--
- - - - - - - - - - - - - - - - - - - - - - -O-u-t-l-i-n-e-d-B-u-t-t-o-n-.-i-c-o-n-(--
- - - - - - - - - - - - - - - - - - - - - - - - -o-n-P-r-e-s-s-e-d-:- -(-)- -{--
- - - - - - - - - - - - - - - - - - - - - - - - - - -S-c-a-f-f-o-l-d-M-e-s-s-e-n-g-e-r-.-o-f-(-c-o-n-t-e-x-t-)-.-s-h-o-w-S-n-a-c-k-B-a-r-(--
- - - - - - - - - - - - - - - - - - - - - - - - - - - - -c-o-n-s-t- -S-n-a-c-k-B-a-r-(-c-o-n-t-e-n-t-:- -T-e-x-t-(-"-V-e-n-t-a- -p-o-r- -p-r-o-d-u-c-t-o-s-:- -p-r-Ã-³-x-i-m-o-.-"-)-)-,--
- - - - - - - - - - - - - - - - - - - - - - - - - - -)-;--
- - - - - - - - - - - - - - - - - - - - - - - - -}-,--
- - - - - - - - - - - - - - - - - - - - - - - - -i-c-o-n-:- -c-o-n-s-t- -I-c-o-n-(-I-c-o-n-s-.-s-h-o-p-p-i-n-g-_-c-a-r-t-_-c-h-e-c-k-o-u-t-_-r-o-u-n-d-e-d-)-,--
- - - - - - - - - - - - - - - - - - - - - - - - -l-a-b-e-l-:- -c-o-n-s-t- -T-e-x-t-(-"-V-e-n-t-a- -p-o-r- -p-r-o-d-u-c-t-o-s-"-)-,--
- - - - - - - - - - - - - - - - - - - - - - -)-,--
- - - - - - - - - - - - - - - - - - - - -]-,--
- - - - - - - - - - - - - - - - - - -)-,--
- - - - - - - - - - - - - - - - -]-)-,--
- - - - - - - - - - - - - - -)-,--
- - - - - - - - - - - - -)-,--
- - - - - - - - - - -]-,--
- - - - - - - - -)-,--
- - - - - - -)-,--
- - - - -)-;--
- - -}--
-}--
--
-c-l-a-s-s- -_-P-r-o-d-u-c-t-i-o-n-S-c-r-e-e-n- -e-x-t-e-n-d-s- -S-t-a-t-e-l-e-s-s-W-i-d-g-e-t- -{--
- - -c-o-n-s-t- -_-P-r-o-d-u-c-t-i-o-n-S-c-r-e-e-n-(-)-;--
--
- - -@-o-v-e-r-r-i-d-e--
- - -W-i-d-g-e-t- -b-u-i-l-d-(-B-u-i-l-d-C-o-n-t-e-x-t- -c-o-n-t-e-x-t-)- -{--
- - - - -r-e-t-u-r-n- -c-o-n-s-t- -C-e-n-t-e-r-(--
- - - - - - -c-h-i-l-d-:- -T-e-x-t-(--
- - - - - - - - -"-P-r-o-d-u-c-c-i-Ã-³-n- -(-p-r-Ã-³-x-i-m-o-)-\-n-R-e-c-e-t-a-s-/-B-O-M- -â-€-¢- -L-o-t-e-s- -â-€-¢- -C-o-n-s-u-m-o- -d-e- -i-n-v-e-n-t-a-r-i-o-"-,--
- - - - - - - - -t-e-x-t-A-l-i-g-n-:- -T-e-x-t-A-l-i-g-n-.-c-e-n-t-e-r-,--
- - - - - - - - -s-t-y-l-e-:- -T-e-x-t-S-t-y-l-e-(-c-o-l-o-r-:- -C-o-l-o-r-s-.-b-l-a-c-k-5-4-)-,--
- - - - - - -)-,--
- - - - -)-;--
- - -}--
-}--
--
-c-l-a-s-s- -_-S-t-a-t-C-a-r-d- -e-x-t-e-n-d-s- -S-t-a-t-e-l-e-s-s-W-i-d-g-e-t- -{--
- - -f-i-n-a-l- -S-t-r-i-n-g- -t-i-t-l-e-;--
- - -f-i-n-a-l- -S-t-r-i-n-g- -v-a-l-u-e-;--
- - -f-i-n-a-l- -I-c-o-n-D-a-t-a- -i-c-o-n-;--
- - -c-o-n-s-t- -_-S-t-a-t-C-a-r-d-(-{-r-e-q-u-i-r-e-d- -t-h-i-s-.-t-i-t-l-e-,- -r-e-q-u-i-r-e-d- -t-h-i-s-.-v-a-l-u-e-,- -r-e-q-u-i-r-e-d- -t-h-i-s-.-i-c-o-n-}-)-;--
--
- - -@-o-v-e-r-r-i-d-e--
- - -W-i-d-g-e-t- -b-u-i-l-d-(-B-u-i-l-d-C-o-n-t-e-x-t- -c-o-n-t-e-x-t-)- -{--
- - - - -f-i-n-a-l- -s-c-h-e-m-e- -=- -T-h-e-m-e-.-o-f-(-c-o-n-t-e-x-t-)-.-c-o-l-o-r-S-c-h-e-m-e-;--
- - - - -r-e-t-u-r-n- -S-i-z-e-d-B-o-x-(--
- - - - - - -w-i-d-t-h-:- -2-4-0-,--
- - - - - - -h-e-i-g-h-t-:- -1-0-0-,--
- - - - - - -c-h-i-l-d-:- -C-a-r-d-(--
- - - - - - - - -c-h-i-l-d-:- -P-a-d-d-i-n-g-(--
- - - - - - - - - - -p-a-d-d-i-n-g-:- -c-o-n-s-t- -E-d-g-e-I-n-s-e-t-s-.-a-l-l-(-1-4-)-,--
- - - - - - - - - - -c-h-i-l-d-:- -R-o-w-(--
- - - - - - - - - - - - -c-h-i-l-d-r-e-n-:- -[--
- - - - - - - - - - - - - - -C-o-n-t-a-i-n-e-r-(--
- - - - - - - - - - - - - - - - -w-i-d-t-h-:- -4-4-,--
- - - - - - - - - - - - - - - - -h-e-i-g-h-t-:- -4-4-,--
- - - - - - - - - - - - - - - - -d-e-c-o-r-a-t-i-o-n-:- -B-o-x-D-e-c-o-r-a-t-i-o-n-(--
- - - - - - - - - - - - - - - - - - -c-o-l-o-r-:- -s-c-h-e-m-e-.-s-e-c-o-n-d-a-r-y-.-w-i-t-h-O-p-a-c-i-t-y-(-0-.-2-2-)-,--
- - - - - - - - - - - - - - - - - - -b-o-r-d-e-r-R-a-d-i-u-s-:- -B-o-r-d-e-r-R-a-d-i-u-s-.-c-i-r-c-u-l-a-r-(-1-4-)-,--
- - - - - - - - - - - - - - - - -)-,--
- - - - - - - - - - - - - - - - -c-h-i-l-d-:- -I-c-o-n-(-i-c-o-n-,- -c-o-l-o-r-:- -s-c-h-e-m-e-.-t-e-r-t-i-a-r-y-)-,--
- - - - - - - - - - - - - - -)-,--
- - - - - - - - - - - - - - -c-o-n-s-t- -S-i-z-e-d-B-o-x-(-w-i-d-t-h-:- -1-2-)-,--
- - - - - - - - - - - - - - -E-x-p-a-n-d-e-d-(--
- - - - - - - - - - - - - - - - -c-h-i-l-d-:- -C-o-l-u-m-n-(--
- - - - - - - - - - - - - - - - - - -c-r-o-s-s-A-x-i-s-A-l-i-g-n-m-e-n-t-:- -C-r-o-s-s-A-x-i-s-A-l-i-g-n-m-e-n-t-.-s-t-a-r-t-,--
- - - - - - - - - - - - - - - - - - -m-a-i-n-A-x-i-s-A-l-i-g-n-m-e-n-t-:- -M-a-i-n-A-x-i-s-A-l-i-g-n-m-e-n-t-.-c-e-n-t-e-r-,--
- - - - - - - - - - - - - - - - - - -c-h-i-l-d-r-e-n-:- -[--
- - - - - - - - - - - - - - - - - - - - -T-e-x-t-(-t-i-t-l-e-,- -s-t-y-l-e-:- -c-o-n-s-t- -T-e-x-t-S-t-y-l-e-(-c-o-l-o-r-:- -C-o-l-o-r-s-.-b-l-a-c-k-5-4-)-)-,--
- - - - - - - - - - - - - - - - - - - - -c-o-n-s-t- -S-i-z-e-d-B-o-x-(-h-e-i-g-h-t-:- -4-)-,--
- - - - - - - - - - - - - - - - - - - - -T-e-x-t-(-v-a-l-u-e-,--
- - - - - - - - - - - - - - - - - - - - - - - - -s-t-y-l-e-:- -c-o-n-s-t- -T-e-x-t-S-t-y-l-e-(-f-o-n-t-W-e-i-g-h-t-:- -F-o-n-t-W-e-i-g-h-t-.-w-9-0-0-,- -f-o-n-t-S-i-z-e-:- -1-8-)-)-,--
- - - - - - - - - - - - - - - - - - -]-,--
- - - - - - - - - - - - - - - - -)-,--
- - - - - - - - - - - - - - -)-,--
- - - - - - - - - - - - -]-,--
- - - - - - - - - - -)-,--
- - - - - - - - -)-,--
- - - - - - -)-,--
- - - - -)-;--
- - -}--
-}--
--
-
